In [3]:
import torch

In [5]:
a = torch.ones(3)

In [6]:
a

tensor([1., 1., 1.])

In [8]:
a[0]

tensor(1.)

In [9]:
a[1]

tensor(1.)

In [10]:
a[2] = 3

In [11]:
a

tensor([1., 1., 3.])

In [12]:
points = torch.tensor([[4,2], [5,1], [6,4]])

In [14]:
points

tensor([[4, 2],
        [5, 1],
        [6, 4]])

In [13]:
points.shape

torch.Size([3, 2])

In [15]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [16]:
points

tensor([[4, 2],
        [5, 1],
        [6, 4]])

In [19]:
points[1:2]

tensor([[5, 1]])

In [23]:
points.unsqueeze(dim=0)

tensor([[[4, 2],
         [5, 1],
         [6, 4]]])

In [26]:
a = torch.tensor([[1,2,3]])
a

tensor([[1, 2, 3]])

In [27]:
b = torch.tensor([[20], [30], [40]])

In [28]:
b.shape

torch.Size([3, 1])

In [29]:
a * b

tensor([[ 20,  40,  60],
        [ 30,  60,  90],
        [ 40,  80, 120]])

In [32]:
torch.zeros(10,2).to(torch.double)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [35]:
torch.ones(10).dtype

torch.float32

In [36]:
a = torch.zeros(3,2)

In [39]:
torch.transpose(a, 0,1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [40]:
points = torch.tensor([[4,2], [5,3], [6,4]])

In [42]:
points_storage = points.storage()
points_storage

 4
 2
 5
 3
 6
 4
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [43]:
points_storage[0]

4

In [44]:
a = torch.ones(3,2)

In [45]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [46]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [47]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [48]:
points.stride()

(2, 1)

In [49]:
points

tensor([[4, 2],
        [5, 3],
        [6, 4]])

In [53]:
points[1].storage_offset()

2

In [54]:
points.storage_offset()

0

In [55]:
points[1].stride()

(1,)

In [56]:
points[1].size()

torch.Size([2])

In [62]:
points.storage()

 4
 2
 5
 3
 6
 4
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [63]:
points.is_contiguous()

True

In [65]:
points.t().is_contiguous()

False

In [66]:
torch.mps

<module 'torch.mps' from '/Users/phamanhdung/Documents/learning/deeplearning-with-pytorch/.venv/lib/python3.12/site-packages/torch/mps/__init__.py'>

In [68]:
points_gpu = torch.tensor([[4,2], [2,3], [5,6]], device='mps')

In [69]:
points_gpu

tensor([[4, 2],
        [2, 3],
        [5, 6]], device='mps:0')

In [71]:
points = points * 2

In [72]:
points_gpu = points.to(device='mps')

In [73]:
points_gpu

tensor([[ 8,  4],
        [10,  6],
        [12,  8]], device='mps:0')

In [75]:
points.to(torch.float)

tensor([[ 8.,  4.],
        [10.,  6.],
        [12.,  8.]])

In [76]:
points = torch.ones(3,4)

In [80]:
points_np = points.numpy()

In [85]:
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [81]:
points = torch.from_numpy(points_np)

In [84]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [88]:
points_gpu.device

device(type='mps', index=0)

In [90]:
torch.save(points, '../chapter3/ourpoints.t')

In [91]:
loaded_points = torch.load('../chapter3/ourpoints.t')

In [92]:
loaded_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [93]:
import h5py

In [94]:
f = h5py.File('../chapter3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [95]:
f = h5py.File('../chapter3/ourpoints.hdf5', 'r')
dset = f['coords']

In [98]:
torch.from_numpy(dset[-2])

tensor([1., 1., 1., 1.])

In [99]:
a = torch.tensor(list(range(9)))

In [100]:
a.shape

torch.Size([9])

In [102]:
a.stride()

(1,)

In [103]:
a.storage_offset()

0

In [104]:
a.view(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [105]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [106]:
b = a.view(3,3)

In [110]:
id(b.storage()) == id(a.storage())

True

In [108]:
b.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]